routes/web.php
<?php

use App\Http\Controllers\AdController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Интерфейс для добавления и вывода объявлений

Route::get('/', function () {
    return redirect()->route('ads.index');
});

Route::resource('ads', AdController::class)->only([
    'index', 'store', 'show'
]);

app/Models/Ad.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Arr;

class Ad extends Model
{
    protected $fillable = [
        'name',
        'description',
        'price',
        'images'
    ];

    protected $casts = [
        'images' => 'array',
        'images_uploaded' => 'array'
    ];

    /**
     * Первая пользовательская ссылка на изображение
     * @todo: не отдавать несуществующее изображение, или возвращать загруженное по ссылке изображение
     * @return string
     */
    public function getImageAttribute()
    {
        return Arr::first($this->images);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AdController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreAd;
use App\Models\Ad;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class AdController extends Controller
{
    /**
     * Вывод списка объявлений с пагинацией и сортировкой
     *
     * @param Request $request
     * @return Factory|View
     */
    public function index(Request $request)
    {
        $adsQuery = Ad::query();

        if ($orderBy = $request->get('orderBy')) {
            $adsQuery = $adsQuery->orderBy($orderBy, $request->get('orderDirection', 'asc'));
        }

        return view('ad.index', [
            'ads' => $adsQuery->paginate(10), ['*'], 'page', $request->get('page'),
            'imagesMaxCount' => StoreAd::IMAGES_MAX_COUNT
        ]);
    }

    /**
     * Добавление нового объявления
     *
     * @param StoreAd $request
     * @return Response
     */
    public function store(StoreAd $request)
    {
        Ad::create($request->validated());

        return redirect()->route('ads.index');
    }

    /**
     * Вывод отдельного объявления
     *
     * @param int $id
     * @return Response
     */
    public function show($id)
    {
        return Ad::findOrFail($id);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/ad/index.blade.php
<!doctype html>
<html>
<head>
    <title>Доска объявлений</title>
    <style type="text/css">
        body {
            width: 800px;
        }

        .ads-order-by a {
            display: block;
        }

        .ads-list {
            padding: 10px 0;
            margin: 20px 0;
            border-top: 1px solid #000;
            border-bottom: 1px solid #000;
        }

        .ads-item:not(:last-child) {
            border-bottom: 1px solid #ccc;
        }

        .ads-store-form {
            width: 600px;
        }

        .ads-store-form input,
        .ads-store-form textarea {
            display: block;
            margin-bottom: 10px;
        }

        .ads-store-form textarea {
            width: 100%;
        }
    </style>
</head>
<body style="width: 800px;">
@if ($ads->count())
    <div class="ads-order-by">
        <span>Сортировать по:</span>
        <a href="?orderBy=price">цене по возрастанию</a>
        <a href="?orderBy=price&orderDirection=desc">цене по убыванию</a>
        <a href="?orderBy=created_at">дате добавления по возрастанию</a>
        <a href="?orderBy=created_at&orderDirection=desc">дате добавления по убыванию</a>
    </div>
    <div class="ads-list">
        @foreach ($ads as $ad)
            <div class="ads-item">
                <p>{{ $ad->name }}</p>
                <p>{{ $ad->description }}</p>
                <p style="font-style: italic">{{ $ad->price }}</p>
                <p><a href="{{ $ad->image }}">{{ $ad->image }}</a></p>
            </div>
        @endforeach
    </div>
    {{ $ads->links() }}
@else
    <p>Объявления отсутствуют.</p>
@endif

<form class="ads-store-form" method="POST" action="{{ route('ads.store') }}">
    @csrf
    <label>
        <span>Название:</span>
        <input name="name">
    </label>
    <label>
        <span>Описание:</span>
        <textarea name="description"></textarea>
    </label>
    <label>
        <span>Цена:</span>
        <input name="price">
    </label>
    <label>
        <span>Ссылки на изображения:</span>
        @for ($i = 1; $i <= $imagesMaxCount; $i++)
            <input name="images[]">
        @endfor
    </label>
    <input type="submit" value="Отправить">
</form>
</body>
</html>